from pydantic import BaseModel, ConfigDict, Field
from typing import Literal, Optional
from sqlalchemy import Column, Integer, String, Boolean, ForeignKey
from sqlalchemy.orm import relationship
from .database import Base

# --- SQLAlchemy Database Models ---

class DBUser(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, unique=True, index=True)
    hashed_password = Column(String)
    
    tasks = relationship("DBTask", back_populates="owner")

class DBTask(Base):
    __tablename__ = "tasks"
    id = Column(Integer, primary_key=True, index=True)
    text = Column(String, index=True)
    priority = Column(String)
    status = Column(String, default="pending")
    confidence = Column(Integer, default=0)
    requires_confirmation = Column(Boolean, default=False)
    ai_output = Column(String, nullable=True)
    
    user_id = Column(Integer, ForeignKey("users.id"))
    owner = relationship("DBUser", back_populates="tasks")

# --- Pydantic Schemas ---

class EmailReplyRequest(BaseModel):
    """
    API payload schema defining requirements for the AI email reply generation endpoint.
    """
    email_text: str = Field(..., description="The content of the email to reply to")
    tone: Literal["formal", "informal"] = Field("formal", description="The tone of the generated reply")

class EmailSendRequest(BaseModel):
    """
    API payload schema governing outbound programmatic email dispatch
    """
    recipient: str = Field(..., description="The target email address of the receiver")
    subject: str = Field(..., description="The subject line of the email")
    message: str = Field(..., description="The literal email body to be dispatched")

class Task(BaseModel):
    """
    Pydantic Schema used for API Validation and Serialization 
    """
    id: int = Field(..., description="Unique identifier for the task")
    text: str = Field(..., description="Description of the task")
    priority: Literal["low", "medium", "high", "auto"] = Field("auto", description="Priority level auto-assigned by NLP or manually specified")
    status: Literal["pending", "completed"] = Field("pending", description="Status")
    confidence: int = Field(0, description="The statistical confidence metric determining the safety of auto-resolution")
    requires_confirmation: bool = Field(False, description="Flag trapping tasks forcing manual human-in-the-loop validation")
    ai_output: str | None = Field(None, description="The results or artifact generated by the AI processing the task")

    model_config = ConfigDict(from_attributes=True)

class UserAuthRequest(BaseModel):
    username: str
    password: str

class TokenResponse(BaseModel):
    access_token: str
    token_type: str
